# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-02 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('street', models.CharField(blank=True, max_length=256, null=True)),
                ('city', models.CharField(blank=True, max_length=64, null=True)),
                ('overall', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=16)),
                ('design', models.FloatField(blank=True, null=True)),
                ('design_description', models.TextField(blank=True, null=True)),
                ('atmosphere', models.FloatField(blank=True, null=True)),
                ('atmosphere_description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
