# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 13:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('street', models.CharField(blank=True, max_length=256, null=True)),
                ('city', models.CharField(blank=True, max_length=64, null=True)),
                ('overall', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=16)),
                ('design', models.FloatField(blank=True, null=True, validators=(django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)))),
                ('design_description', models.TextField(blank=True, null=True)),
                ('atmosphere', models.FloatField(blank=True, null=True, validators=(django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)))),
                ('atmosphere_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'pub',
                'verbose_name_plural': 'pubs',
            },
        ),
    ]
